# Generated by Django 6.0.4 on 2026-04-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alpha_missense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('protein_variant', models.CharField(blank=True, max_length=128, null=True)),
                ('uniprot_id', models.CharField(blank=True, max_length=128, null=True)),
                ('am_pathogenicity', models.IntegerField()),
                ('am_class', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': '"alpha_missense_db"."alpha_missense"',
                'managed': False,
            },
        ),
    ]
