"""
Django settings for crispr_webapp project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import tempfile


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1x2@o)tu9^t&mk+%aw3i)9xbwdyt5fe%j1z4=li&-ob)3xz#s9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'designer.apps.DesignerConfig',
    'saffron.apps.SaffronConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crispr_webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crispr_webapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR/'db.sqlite3'
    },
    'legacy_db':{
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':'swpdb',
        'USER':'swp2026',
        'PASSWORD':'swp2026',
        # 'HOST':'127.0.0.1',
        'HOST':'medgen_pgsql_db',
        'PORT':'5432',
        'OPTIONS':{
            'options': '-c search_path=alpha_missense_db' # Set search path to target schema
        }
    }
}
#DATABASE_ROUTERS = ['medgen_lab_proj.db_router.LegacyDBRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / 'designer' / 'static',
    BASE_DIR / 'saffron' / 'static',
]

# SignalP 6.0 (local CLI in a Python 3.10 sidecar — not the Django 3.12 env)
SIGNALP6_BIN = os.getenv('SIGNALP6_BIN', 'signalp6')
SIGNALP6_MODEL_DIR = os.getenv('SIGNALP6_MODEL_DIR', None)
SIGNALP_CACHE_DIR = os.getenv('SIGNALP_CACHE_DIR', None)
SIGNALP_TIMEOUT_SEC = int(os.getenv('SIGNALP_TIMEOUT_SEC', '600'))
ENSEMBL_TIMEOUT_SEC = int(os.getenv('ENSEMBL_TIMEOUT_SEC', '60'))
# Gutierrez Guarnizo et al. SP pathogenic-variant catalogue (optional)
PATHO_SPV_CSV = os.getenv(
    'PATHO_SPV_CSV',
    str(BASE_DIR / 'files-archive-dir' / 'patho_spv_in_hs' / 'patho_SPVs_in_hs.csv'),
)

# ---- Enable subpath deployment ----
FORCE_SCRIPT_NAME = os.getenv('FORCE_SCRIPT_NAME', None)
# 2. Construct STATIC_URL dynamically
if FORCE_SCRIPT_NAME:
    # This makes the browser ask for /kuechleo/static/...
    STATIC_URL = f"{FORCE_SCRIPT_NAME.rstrip('/')}/static/"
else:
    STATIC_URL = '/static/'

# This is where files go for PRODUCTION, but we define it so the helpers don't crash
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Ensure Django knows it's behind a proxy for HTTPS detection
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True



# Local data directory (cache, etc.)
DATA_DIR = BASE_DIR / 'data'
SCREEN_DATA_DIR = BASE_DIR / 'files-archive-dir'


def _resolve_cache_dir() -> Path:
    """Pick a cache directory the app process can write to (Docker bind mounts may be read-only)."""
    candidates = []
    env_dir = os.environ.get('DJANGO_CACHE_DIR')
    if env_dir:
        candidates.append(Path(env_dir))
    candidates.append(DATA_DIR / 'cache')
    candidates.append(Path(tempfile.gettempdir()) / 'amber_django_cache')

    for path in candidates:
        try:
            path.mkdir(parents=True, exist_ok=True)
            probe = path / '.write_probe'
            probe.write_text('ok', encoding='utf-8')
            probe.unlink(missing_ok=True)
            return path
        except OSError:
            continue

    fallback = Path(tempfile.gettempdir()) / 'amber_django_cache'
    fallback.mkdir(parents=True, exist_ok=True)
    return fallback


CACHE_DIR = _resolve_cache_dir()
DATA_DIR.mkdir(parents=True, exist_ok=True)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': str(CACHE_DIR),
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

print(f"DEBUG: FORCE_SCRIPT_NAME is {FORCE_SCRIPT_NAME}")
print(f"DEBUG: STATIC_URL is {STATIC_URL}")
